In [10]:
import torch

def function01(tensor: torch.Tensor, count_over: str):
    return torch.mean(tensor, 1 if count_over == "rows" else 0)

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([1.5000, 3.5000])
tensor([2., 3.])


In [19]:
data = [[1, 2, 3],[3, 4, 5]]
x_data = torch.tensor(data,  dtype=torch.float32)
x_data

print(x_data)
print(torch.mean(x_data))
print(torch.mean(x_data, 1))
print(torch.mean(x_data, 0))

tensor([[1., 2., 3.],
        [3., 4., 5.]])
tensor(3.)
tensor([2., 4.])
tensor([2., 3., 4.])


In [37]:
def function02(tensor: torch.Tensor):
    return torch.rand(tensor.shape[1],  dtype=torch.float32, requires_grad=True)

In [38]:
function02(x_data)

tensor([0.8873, 0.7728, 0.6926], requires_grad=True)

In [39]:
x_data.shape

torch.Size([2, 3])

In [44]:
n_features = 2
n_objects = 300

w_true = torch.randn(n_features)
X_ = (torch.rand(n_objects, n_features) - 0.5) * 5
Y_ = X @ w_true + torch.randn(n_objects) / 2

In [45]:
X_

tensor([[ 0.4215,  0.7981],
        [-1.9449, -1.3582],
        [ 0.7416,  0.6704],
        [-1.0130, -0.8734],
        [ 2.1253, -2.2356],
        [ 1.3022, -1.7311],
        [-0.1479, -1.7062],
        [ 2.2408, -0.5508],
        [ 1.1386,  2.3574],
        [ 1.1316,  1.3112],
        [ 1.5271,  2.1541],
        [ 1.0807,  0.6629],
        [ 1.0989,  0.6114],
        [ 1.2841, -1.7402],
        [ 1.2261, -0.7305],
        [-0.8373, -2.2877],
        [ 2.1306, -2.0623],
        [-1.9746, -1.1575],
        [ 1.3692,  0.3104],
        [ 1.6299,  1.3177],
        [-1.1749, -1.9921],
        [-1.3536,  0.4968],
        [-0.3653, -1.7907],
        [-0.9898, -2.2873],
        [-1.3820,  1.5273],
        [-1.9223, -2.0634],
        [ 2.2349, -1.0324],
        [-2.3668, -1.5102],
        [-2.2901,  0.6277],
        [-0.2082, -1.5470],
        [-0.1303, -1.7556],
        [-1.4346,  0.8270],
        [-0.3627,  0.4069],
        [ 1.6743, -0.1509],
        [-0.6629, -2.0876],
        [ 1.6617,  0

In [46]:
Y_

tensor([-2.4604,  1.5687,  2.3350, -2.4711, -0.7363,  0.2807, -1.3611,  2.1274,
        -1.8462,  2.6722, -0.2268,  0.0276,  0.4398, -2.3864, -0.1566, -0.2776,
        -2.8566,  1.2537,  0.2330, -0.4246,  3.0904,  1.8748, -0.3864, -0.7458,
         0.7052, -2.6154,  1.4008,  1.1660, -1.7154,  1.9788,  0.6895, -0.9499,
         0.0626, -0.8597,  1.2560,  2.2859,  1.1694,  1.4983, -0.2454,  1.3787,
         0.6660,  0.3746, -1.3745, -1.4313, -0.6253, -1.0925,  0.6391, -0.5458,
        -1.3394, -1.6755, -1.5150,  0.5826,  2.5383,  1.6803,  1.5774, -2.5621,
         1.7567, -2.8176,  0.6797,  2.2173, -2.3887, -1.8281,  2.2697,  0.5616,
        -2.4370,  1.4828, -2.0342,  1.5264, -0.9033, -2.1954, -2.0353, -0.0193,
         2.1339, -0.6440,  0.8676, -1.0541, -1.7923, -0.3691,  0.9686,  1.1526,
         0.3052, -0.3767,  0.4965, -1.2321,  0.3534, -1.2470, -1.1115,  0.8228,
        -0.2353,  0.3177, -2.1041, -2.0408, -2.7440,  0.0239, -0.8204,  1.7397,
         1.6053, -0.0158, -0.5857,  2.40

In [47]:
n_steps = 50
step_size = 1e-2

def function03(x: torch.Tensor, y: torch.Tensor):
    w = function02(x)

    for i in range(n_steps):
        w.requires_grad = True

        Y_pred = x @ w

        mse = torch.mean((Y_pred - y) ** 2)

        print(f'MSE на шаге {i+1} {mse.item():.5f}')

        mse.backward()

        with torch.no_grad():
            w = w - w.grad * step_size
            
    return w

In [48]:
function03(X_,Y_)

MSE на шаге 1 3.28079
MSE на шаге 2 3.19135
MSE на шаге 3 3.10896
MSE на шаге 4 3.03306
MSE на шаге 5 2.96312
MSE на шаге 6 2.89867
MSE на шаге 7 2.83929
MSE на шаге 8 2.78456
MSE на шаге 9 2.73412
MSE на шаге 10 2.68763
MSE на шаге 11 2.64478
MSE на шаге 12 2.60529
MSE на шаге 13 2.56887
MSE на шаге 14 2.53530
MSE на шаге 15 2.50435
MSE на шаге 16 2.47582
MSE на шаге 17 2.44950
MSE на шаге 18 2.42524
MSE на шаге 19 2.40286
MSE на шаге 20 2.38223
MSE на шаге 21 2.36319
MSE на шаге 22 2.34564
MSE на шаге 23 2.32945
MSE на шаге 24 2.31451
MSE на шаге 25 2.30073
MSE на шаге 26 2.28802
MSE на шаге 27 2.27629
MSE на шаге 28 2.26547
MSE на шаге 29 2.25549
MSE на шаге 30 2.24628
MSE на шаге 31 2.23777
MSE на шаге 32 2.22993
MSE на шаге 33 2.22269
MSE на шаге 34 2.21601
MSE на шаге 35 2.20984
MSE на шаге 36 2.20415
MSE на шаге 37 2.19890
MSE на шаге 38 2.19405
MSE на шаге 39 2.18957
MSE на шаге 40 2.18544
MSE на шаге 41 2.18163
MSE на шаге 42 2.17810
MSE на шаге 43 2.17485
MSE на шаге 44 2.171

tensor([0.0911, 0.0734])

In [49]:
from torch import nn

def create_linear():
    return nn.Linear(in_features=10, out_features=100, bias=False)

In [50]:
create_linear()

Linear(in_features=10, out_features=100, bias=False)

In [51]:
import torch
from torch import nn

def count_parameters(layer: nn.Module):
    return sum(torch.numel(p) for p in layer.parameters() if p.requires_grad)

In [64]:
[p.requires_grad for p in create_linear().parameters()]

[True]

In [81]:
import torch
from torch import nn

def function02(tensor: torch.Tensor):
    return torch.rand(tensor.shape[1],  dtype=torch.float32, requires_grad=True)

step_size = 1e-2

def function04(x: torch.Tensor, y: torch.Tensor):
    model = nn.Linear(in_features=x.shape[1], out_features=1, bias=False)    
    
    w = function02(x)
    i = 0

    while True:
        w.requires_grad = True

        Y_pred = x @ w

        mse = torch.mean((Y_pred - y) ** 2)

        print(f'MSE на шаге {i+1} {mse.item():.5f}')
        
        if mse.item() < 0.3:
            break
            
        i += 1

        mse.backward()

        with torch.no_grad():
            w = w - w.grad * step_size
            
    model.weight = nn.Parameter(w)
            
    return model

In [82]:
n_features = 2
n_objects = 300

w_true = torch.randn(n_features)
X = (torch.rand(n_objects, n_features) - 0.5) * 5
Y = X @ w_true + torch.randn(n_objects) / 2

In [83]:
Y.shape

torch.Size([300])

In [84]:
test = nn.Linear(in_features=2, out_features=1, bias=False)

In [85]:
function04(X,Y)

MSE на шаге 1 4.72984
MSE на шаге 2 4.35729
MSE на шаге 3 4.01548
MSE на шаге 4 3.70186
MSE на шаге 5 3.41411
MSE на шаге 6 3.15009
MSE на шаге 7 2.90784
MSE на шаге 8 2.68557
MSE на шаге 9 2.48163
MSE на шаге 10 2.29450
MSE на шаге 11 2.12281
MSE на шаге 12 1.96526
MSE на шаге 13 1.82071
MSE на шаге 14 1.68807
MSE на шаге 15 1.56636
MSE на шаге 16 1.45469
MSE на шаге 17 1.35222
MSE на шаге 18 1.25819
MSE на шаге 19 1.17191
MSE на шаге 20 1.09274
MSE на шаге 21 1.02010
MSE на шаге 22 0.95344
MSE на шаге 23 0.89227
MSE на шаге 24 0.83614
MSE на шаге 25 0.78463
MSE на шаге 26 0.73737
MSE на шаге 27 0.69400
MSE на шаге 28 0.65420
MSE на шаге 29 0.61767
MSE на шаге 30 0.58416
MSE на шаге 31 0.55341
MSE на шаге 32 0.52518
MSE на шаге 33 0.49928
MSE на шаге 34 0.47552
MSE на шаге 35 0.45371
MSE на шаге 36 0.43369
MSE на шаге 37 0.41532
MSE на шаге 38 0.39847
MSE на шаге 39 0.38300
MSE на шаге 40 0.36881
MSE на шаге 41 0.35578
MSE на шаге 42 0.34382
MSE на шаге 43 0.33285
MSE на шаге 44 0.322

Linear(in_features=2, out_features=1, bias=False)

In [112]:
import torch
from torch import nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
from torch import optim
from torch.optim import Optimizer

def create_model():
    return nn.Sequential(
    nn.Linear(100, 10),
    nn.ReLU(),
    nn.Linear(10, 1)
)

def train(model: nn.Module, data_loader: DataLoader, optimizer: Optimizer, loss_fn):
    losses = []

    model.train()

    for x, y in data_loader:
        optimizer.zero_grad()
        output = model(x)
        loss = loss_fn(output, y)
        loss.backward()
        print(f'{loss.item():.5f}')       
        losses.append(loss.item())
        optimizer.step()

    return sum(losses)/len(losses)

def evaluate(model: nn.Module, data_loader: DataLoader, loss_fn):
    losses = []

    with torch.inference_mode():
        for x, y in data_loader:
            output = model(x)
            loss = loss_fn(output, y)
            losses.append(loss.item())

    return sum(losses)/len(losses)

n_features = 2
n_objects = 300

torch.manual_seed(0);

w_true = torch.randn(n_features)

X = (torch.rand(n_objects, n_features) - 0.5) * 10
X *= (torch.arange(n_features) * 2 + 1)
Y = (X @ w_true + torch.randn(n_objects)).unsqueeze(1)

model_ = nn.Linear(2, 1)

optimizer_ = optim.Adam(model_.parameters(), lr=1e-1)

loss_fn_ = nn.MSELoss()

dataset_ = TensorDataset(X, Y)

loader_ = DataLoader(dataset_, batch_size=4, shuffle=True)

# train(model_, loader_, optimizer_,  loss_fn_)
evaluate(model_, loader_, loss_fn_)

29.233508405685424

In [97]:
a = [11,22,33]
for i, x in enumerate(a):
    print(i,x)

0 11
1 22
2 33
